#!/bin/bash

set -e

if [ "$NGINX_VERSION" == "" ]; then
  echo "must set NGINX_VERSION, i.e NGINX_VERSION=1.2.0"
  exit 1
fi

cd contrib

# download and extract nginx
curl -L http://nginx.org/download/nginx-$NGINX_VERSION.tar.gz -o - | tar xz

pushd ngx_pagespeed-$PAGESPEED_VERSION
curl -L https://dl.google.com/dl/page-speed/psol/1.7.30.4.tar.gz -o - | tar xz
popd

cd nginx-$NGINX_VERSION

./configure --prefix=/app/vendor/nginx --with-pcre=../pcre-8.32 --with-http_ssl_module --with-http_gzip_static_module --with-http_stub_status_module --add-module=../ngx_pagespeed-$PAGESPEED_VERSION && make install

# build and package nginx for heroku
# vulcan build -v -s nginx-$NGINX_VERSION -o $tempdir/nginx-$NGINX_VERSION-heroku.tar.gz -p /app/vendor/nginx -c './configure --prefix=/app/vendor/nginx --with-pcre=contrib/pcre-8.32 --with-http_ssl_module --with-http_gzip_static_module --with-http_stub_status_module && make install' 

echo "+ Binaries available at ./nginx-$NGINX_VERSION-heroku.tar.gz"
echo "+ Upload this package to Amazon S3."

# upload to s3
#s3cmd put -rr $tempdir/nginx-$NGINX_VERSION-heroku.tar.gz s3://$S3_BUCKET
