#!/bin/bash

set -e

if [ "$NGINX_VERSION" == "" ]; then
  echo "must set NGINX_VERSION, i.e NGINX_VERSION=1.2.0"
  exit 1
fi

pushd contrib

# download and extract nginx
curl -L http://nginx.org/download/nginx-$NGINX_VERSION.tar.gz -o - | tar xz

pushd ngx_pagespeed-$PAGESPEED_VERSION
curl -L https://dl.google.com/dl/page-speed/psol/1.7.30.4.tar.gz -o - | tar xz
popd

cd nginx-$NGINX_VERSION

./configure --prefix=/app/vendor/nginx --with-pcre=../pcre-8.32 --with-http_ssl_module --with-http_gzip_static_module --with-http_stub_status_module --add-module=../ngx_pagespeed-$PAGESPEED_VERSION && make install

tar -czf nginx-$NGINX_VERSION-heroku.tar.gz -C /app/vendor/nginx .

popd
echo "+ Binaries available at ./nginx-$NGINX_VERSION-heroku.tar.gz"
echo "+ Upload this package to Amazon S3."

# upload to s3
cd support_run/s3cmd-1.0.1
./s3cmd -c s3cfg put -rr contrib/nginx-$NGINX_VERSION/nginx-$NGINX_VERSION-heroku.tar.gz s3://$S3_BUCKET
